project_isg/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project_isg_0.urls')),
]

project_isg_0/urls.py
from django.urls import path,include
from . import views

app_name='project_isg_0'

urlpatterns = [
    path('', views.home,name='home'),
]

project_isg_0/models.py
from django.db import models

# Create your models here.

project_isg_0/forms.py
from django import forms

class TestForm(forms.Form):
    text = forms.CharField(label='文字入力')
    num = forms.IntegerField(label='数量')

project_isg_0/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from .forms import TestForm

# Create your views here.

def home(request):
    my_dict = {
    'insert_something':"views.pyのinsert_something部分です。",
    'name':'yarita',
    'form':TestForm(),
    'insert_forms':'初期値',
    }
    if (request.method == 'POST'):
        my_dict['insert_forms'] = '文字列:' + request.POST['text'] + '<br>整数型:' + request.POST['num']
        my_dict['form'] = TestForm(request.POST)

    return render(request,'project_isg_0/home.html',my_dict)

project_isg_0/templates/project_isg_0/home.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>テストWebアプリ</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
    <script src="{% static 'js/sample.js' %}"></script>
  </head>
  <body>
    <h1>home.htmlを表示しています</h1>
    <img src="{% static "images/img_0.png" %}" alt="表示できません">

    <p>{{ insert_something }}</p>
    <p>作成者は<b id='test'>{{ name }}</b>です。</p>

    <p>{{insert_forms|safe}}</p>
    <table>
        <form action="{% url 'project_isg_0:home' %}" method="post">
            {% csrf_token %}
            <tr><td></td><td>入力フォーム</td></tr>
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" value="送信"></td></tr>
        </form>
    </table>

  </body>
</html>